### ISSUE TITLE
run snmp docker instead of openyuma

### ISSUE THREAD

**Issue by EngKhaled91** [Melacon/WirelessTransportEmulator#7]
Hello everybody
maybe my question is not an issue but, I want to know if I can run anther docker container on top of your simulator like snmp docker daemon instead of OpenYuma like snmp docker from here (https://hub.docker.com/r/polinux/snmpd) or is there any suggestions about how to run pure snmp on top of the WTE. 
thanks for your services

**Comment by alexandrustancu** [comment]
Hi,

You could replace the name of the docker image that is being started from _clean.py_ and _networkelement.py_ from `openyuma` to whatever the name of the container you want to run is.

But the purpose of WTE itself is highly dependent on OpenYuma. Without it, I don't know why you would need all this overhead just for running snmp. If you would like to have personalised data inside each snmpd, then it is more complex than that.

BR,
Alex

**Comment by demx8as6** [comment]
Done 😉

 

Von: Alex Stancu <notifications@github.com> 
Gesendet: Montag, 25. März 2019 12:31
An: Melacon/WirelessTransportEmulator <WirelessTransportEmulator@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [Melacon/WirelessTransportEmulator] run snmp docker instead of openyuma (#7)

 

Hi,

You could replace the name of the docker image that is being started from clean.py and networkelement.py from openyuma to whatever the name of the container you want to run is.

But the purpose of WTE itself is highly dependent on OpenYuma. Without it, I don't know why you would need all this overhead just for running snmp. If you would like to have personalised data inside each snmpd, then it is more complex than that.

BR,
Alex
